### ISSUE TITLE
Wrong error handling

### ISSUE THREAD

**Issue by anotheri** [stoprocent/node-itunesconnect#2]
at the moment iTunes connect is unavailable until December 29 — https://itunesconnect.apple.com/iTCShutdown.html

it throws the next uncaughtException:
```
uncaughtException: Cannot read property 'headers' of undefined date=Mon Dec 22 2014 18:55:09 GMT+0000 (UTC)
...
stack=[
  TypeError: Cannot read property 'headers' of undefined,
  at Request._callback (/opt/proj/node_modules/itunesconnect/index.js:287:26),
  at self.callback (/opt/proj/node_modules/itunesconnect/node_modules/request/request.js:123:22),
  at Request.emit (events.js:95:17),
  at ClientRequest.self.clientErrorHandler (/opt/proj/node_modules/itunesconnect/node_modules/request/request.js:244:10),
  at ClientRequest.emit (events.js:95:17),
  at CleartextStream.socketErrorListener (http.js:1547:9),
  at CleartextStream.emit (events.js:95:17),
  at Socket.onerror (tls.js:1440:17),
  at Socket.emit (events.js:117:20),
  at net.js:833:16
]
```

**Comment by anotheri** [comment]
@stoprocent could you publish updated version to NPM, please?

**Comment by stoprocent** [comment]
Sure @anotheri. It's updated now!

**Comment by anotheri** [comment]
thank you! :)
